// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from_str`, `from`

class Bolt11Invoice {
  final String encoded;
  final BigInt? amount;
  final String description;
  final String paymentHash;
  final BigInt expiresAt;
  final String payee;

  const Bolt11Invoice({
    required this.encoded,
    this.amount,
    required this.description,
    required this.paymentHash,
    required this.expiresAt,
    required this.payee,
  });

  @override
  int get hashCode =>
      encoded.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      paymentHash.hashCode ^
      expiresAt.hashCode ^
      payee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bolt11Invoice &&
          runtimeType == other.runtimeType &&
          encoded == other.encoded &&
          amount == other.amount &&
          description == other.description &&
          paymentHash == other.paymentHash &&
          expiresAt == other.expiresAt &&
          payee == other.payee;
}
