// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class Error with _$Error implements FrbException {
  const Error._();

  const factory Error.cdk(
    String field0,
  ) = Error_Cdk;
  const factory Error.database(
    String field0,
  ) = Error_Database;
  const factory Error.hex(
    String field0,
  ) = Error_Hex;
  const factory Error.protocol(
    String field0,
  ) = Error_Protocol;
  const factory Error.url(
    String field0,
  ) = Error_Url;
}
