// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Uint8List generateSeed() => RustLib.instance.api.crateApiKeyGenerateSeed();

String generateHexSeed() => RustLib.instance.api.crateApiKeyGenerateHexSeed();

String deriveSharedSecret({required String secret, required String pubKey}) =>
    RustLib.instance.api
        .crateApiKeyDeriveSharedSecret(secret: secret, pubKey: pubKey);

String getPubKey({required String secret}) =>
    RustLib.instance.api.crateApiKeyGetPubKey(secret: secret);

Uint8List keyHexToBytes({required String key}) =>
    RustLib.instance.api.crateApiKeyKeyHexToBytes(key: key);

String keyBytesToHex({required List<int> key}) =>
    RustLib.instance.api.crateApiKeyKeyBytesToHex(key: key);
