// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `try_from`, `try_into`

class Token {
  final String encoded;
  final BigInt amount;
  final String mintUrl;

  const Token({
    required this.encoded,
    required this.amount,
    required this.mintUrl,
  });

  static Token parse({required String encoded}) =>
      RustLib.instance.api.crateApiTokenTokenParse(encoded: encoded);

  @override
  int get hashCode => encoded.hashCode ^ amount.hashCode ^ mintUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Token &&
          runtimeType == other.runtimeType &&
          encoded == other.encoded &&
          amount == other.amount &&
          mintUrl == other.mintUrl;
}
